import Footer from '../components/Footer';
import LegalPageHeader from '../components/LegalPageHeader';

function TermsOfService() {
  return (
    <>
      <LegalPageHeader />

      <main className="legal-page">
        <h1>Terms of Service</h1>
        <p className="legal-updated">Last updated: 31 August 2026</p>

        <p>
          These terms govern your use of Job Search 365 ("the Service"),
          provided under the name 365 Applications ("we", "us"). By
          creating an account or using the Service, you agree to these
          terms.
        </p>

        <h2>The Service</h2>
        <p>
          Job Search 365 is a personal job-application tracker: it lets
          you log applications, track their status, store related
          documents, and optionally use AI-assisted features (cover letter
          drafting, CV content reordering, job-listing import, and Gmail
          inbox scanning) to help manage that process.
        </p>

        <h2>Your account</h2>
        <p>
          You're responsible for keeping your login credentials secure and
          for the accuracy of the information you provide. You must be
          able to legally accept these terms to create an account.
        </p>

        <h2>Acceptable use</h2>
        <p>You agree not to:</p>
        <ul>
          <li>Use the Service for any unlawful purpose;</li>
          <li>
            Attempt to disrupt, overload, or gain unauthorized access to
            the Service or other users' data;
          </li>
          <li>
            Upload content you don't have the right to upload, or that
            infringes someone else's rights.
          </li>
        </ul>

        <h2>Your content</h2>
        <p>
          You retain ownership of everything you enter or upload — job
          details, documents, notes. By using the Service you grant us the
          limited right to process that content (including via the
          third-party providers listed in our{' '}
          <a href="/privacy-policy">Privacy Policy</a>) solely to provide
          the features you use.
        </p>

        <h2>AI-assisted features</h2>
        <p>
          Cover letter drafts, CV reordering suggestions, job details
          extracted from a posting URL, and Gmail-to-job matches are
          generated by an AI model and may contain errors, omissions, or
          irrelevant results. Nothing produced by these features is
          applied to your job records automatically — you review and
          confirm every change. You're responsible for checking AI-
          generated content before relying on it, including before sending
          a cover letter or acting on an extracted job detail.
        </p>

        <h2>Third-party services</h2>
        <p>
          The Service relies on third-party providers — Google, DeepSeek,
          Resend, Cloudflare, and Supabase — to operate. Their own terms
          and availability may affect the Service, and we're not
          responsible for their conduct.
        </p>

        <h2>Availability</h2>
        <p>
          This is an independently-run, personal project provided on an
          "as is" and "as available" basis, with no guaranteed uptime.
          Features may change, be added, or be removed at any time.
        </p>

        <h2>Disclaimer and limitation of liability</h2>
        <p>
          The Service is provided without warranties of any kind, express
          or implied. To the fullest extent permitted by law, we are not
          liable for any indirect, incidental, or consequential damages
          arising from your use of the Service, including reliance on
          AI-generated content or the loss of tracked application data.
        </p>

        <h2>Termination</h2>
        <p>
          You can delete your account at any time from your profile page,
          which deletes your account data. We may suspend or terminate
          access for anyone who violates these terms.
        </p>

        <h2>Changes to these terms</h2>
        <p>
          We may update these terms from time to time. Material changes
          will be reflected here with an updated date.
        </p>

        <h2>Governing law</h2>
        <p>These terms are governed by the laws of England and Wales.</p>

        <h2>Contact</h2>
        <p>
          Questions about these terms:{' '}
          <a href="mailto:support@jobsearch365.com">
            support@jobsearch365.com
          </a>
        </p>
      </main>

      <Footer />
    </>
  );
}

export default TermsOfService;
